# Generated by Django 5.0.4 on 2026-04-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0003_datasource_layer_fk_to_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('gee', 'GEE'), ('chirps', 'CHIRPS'), ('wdpa', 'WDPA'), ('osm', 'OSM'), ('imd', 'IMD'), ('opentopo', 'OpenTopography'), ('stac', 'STAC Catalogue'), ('earthaccess', 'NASA Earthaccess'), ('cds', 'Copernicus Data Store')], max_length=20),
        ),
    ]
