# Generated by Django 5.0.4 on 2026-04-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0007_uploadtask'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vectorfeature',
            new_name='layers_vect_layer_i_42ae34_idx',
            old_name='layers_vect_layer_i_idx',
        ),
        migrations.AddField(
            model_name='rasterasset',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rasterasset',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='temporal_type',
            field=models.CharField(choices=[('static', 'Static'), ('daily', 'Daily'), ('annual', 'Annual'), ('monthly', 'Monthly')], default='static', max_length=20),
        ),
    ]
