_RASTER_IN = [{"handle": "raster_in", "dataType": "raster"}]
_RASTER_OUT = [{"handle": "raster_out", "dataType": "raster"}]

NODE_CATALOG = [
    # ── Inputs ────────────────────────────────────────────────────────────────
    {
        "type": "raster_input",
        "label": "Raster Input",
        "category": "input",
        "description": "Load a raster layer by slug",
        "inputs": [],
        "outputs": [{"handle": "raster_out", "dataType": "raster"}],
    },
    {
        "type": "vector_input",
        "label": "Vector Input",
        "category": "input",
        "description": "Load a vector layer by slug",
        "inputs": [],
        "outputs": [{"handle": "vector_out", "dataType": "vector"}],
    },
    # ── Core processing ───────────────────────────────────────────────────────
    {
        "type": "difference",
        "label": "Difference",
        "category": "processing",
        "description": "Subtract raster B from raster A",
        "inputs": [
            {"handle": "raster_a", "dataType": "raster", "label": "A"},
            {"handle": "raster_b", "dataType": "raster", "label": "B"},
        ],
        "outputs": _RASTER_OUT,
    },
    # ── Vegetation indices ────────────────────────────────────────────────────
    {
        "type": "ndvi",
        "label": "NDVI",
        "category": "processing",
        "description": "Normalized Difference Vegetation Index (NIR−Red)/(NIR+Red)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "evi",
        "label": "EVI",
        "category": "processing",
        "description": "Enhanced Vegetation Index — reduces atmospheric distortion",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "savi",
        "label": "SAVI",
        "category": "processing",
        "description": "Soil-Adjusted Vegetation Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "gndvi",
        "label": "GNDVI",
        "category": "processing",
        "description": "Green NDVI — uses green band instead of red",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "rdvi",
        "label": "RDVI",
        "category": "processing",
        "description": "Renormalized Difference Vegetation Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "tvi",
        "label": "TVI",
        "category": "processing",
        "description": "Triangular Vegetation Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "dvi",
        "label": "DVI",
        "category": "processing",
        "description": "Difference Vegetation Index (NIR−Red)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "rvi",
        "label": "RVI",
        "category": "processing",
        "description": "Ratio Vegetation Index (NIR/Red)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "vari",
        "label": "VARI",
        "category": "processing",
        "description": "Visible Atmospherically Resistant Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "avi",
        "label": "AVI",
        "category": "processing",
        "description": "Advanced Vegetation Index — cube-root formulation",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "arvi",
        "label": "ARVI",
        "category": "processing",
        "description": "Atmospherically Resistant Vegetation Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Chlorophyll ────────────────────────────────────────────────────────────
    {
        "type": "cigreen",
        "label": "CI Green",
        "category": "processing",
        "description": "Chlorophyll Index Green (NIR/Green − 1)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "cired",
        "label": "CI Red",
        "category": "processing",
        "description": "Chlorophyll Index Red Edge (NIR/Red − 1)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "ndre",
        "label": "NDRE",
        "category": "processing",
        "description": "Normalized Difference Red Edge",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Soil-adjusted ─────────────────────────────────────────────────────────
    {
        "type": "osavi",
        "label": "OSAVI",
        "category": "processing",
        "description": "Optimized Soil-Adjusted Vegetation Index (L=0.16)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "tsavi",
        "label": "TSAVI",
        "category": "processing",
        "description": "Transformed Soil-Adjusted Vegetation Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Moisture ──────────────────────────────────────────────────────────────
    {
        "type": "ndmi",
        "label": "NDMI",
        "category": "processing",
        "description": "Normalized Difference Moisture Index (NIR−SWIR1)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Water ─────────────────────────────────────────────────────────────────
    {
        "type": "ndwi",
        "label": "NDWI",
        "category": "processing",
        "description": "Normalized Difference Water Index (Green−NIR)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "mndwi",
        "label": "MNDWI",
        "category": "processing",
        "description": "Modified NDWI (Green−SWIR)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "wri",
        "label": "WRI",
        "category": "processing",
        "description": "Water Ratio Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "s3",
        "label": "S3",
        "category": "processing",
        "description": "S3 water index using Green, NIR, SWIR",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Urban / Built-up ──────────────────────────────────────────────────────
    {
        "type": "ui",
        "label": "UI",
        "category": "processing",
        "description": "Urban Index (SWIR2−NIR)/(SWIR2+NIR)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Burn / Fire ───────────────────────────────────────────────────────────
    {
        "type": "nbr",
        "label": "NBR",
        "category": "processing",
        "description": "Normalized Burn Ratio (NIR−SWIR2)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "nbr2",
        "label": "NBR2",
        "category": "processing",
        "description": "Normalized Burn Ratio 2 (SWIR1−SWIR2)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "bai",
        "label": "BAI",
        "category": "processing",
        "description": "Burned Area Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "csi",
        "label": "CSI",
        "category": "processing",
        "description": "Char Soil Index (SWIR1/SWIR2)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Soil / Bare ───────────────────────────────────────────────────────────
    {
        "type": "bsi",
        "label": "BSI",
        "category": "processing",
        "description": "Bare Soil Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Snow ──────────────────────────────────────────────────────────────────
    {
        "type": "ndsi",
        "label": "NDSI",
        "category": "processing",
        "description": "Normalized Difference Snow Index (Green−SWIR)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Turbidity / Sediment ──────────────────────────────────────────────────
    {
        "type": "ndti",
        "label": "NDTI",
        "category": "processing",
        "description": "Normalized Difference Turbidity Index (Red−Green)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Atmospheric ───────────────────────────────────────────────────────────
    {
        "type": "hot",
        "label": "HOT",
        "category": "processing",
        "description": "Haze Optimized Transformation",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "shadow_index",
        "label": "Shadow Index",
        "category": "processing",
        "description": "Shadow Index using visible bands",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Raster utilities ─────────────────────────────────────────────────────
    {
        "type": "reclassify",
        "label": "Reclassify",
        "category": "processing",
        "description": "Reclassify raster values by range rules",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "clip",
        "label": "Clip",
        "category": "processing",
        "description": "Clip raster to vector mask",
        "inputs": [
            {"handle": "raster_in", "dataType": "raster"},
            {"handle": "vector_in", "dataType": "vector"},
        ],
        "outputs": _RASTER_OUT,
    },
    {
        "type": "zonal_stats",
        "label": "Zonal Stats",
        "category": "processing",
        "description": "Compute per-feature raster statistics",
        "inputs": [
            {"handle": "raster_in", "dataType": "raster"},
            {"handle": "vector_in", "dataType": "vector"},
        ],
        "outputs": [{"handle": "vector_out", "dataType": "vector"}],
    },
    # ── Output ────────────────────────────────────────────────────────────────
    {
        "type": "preview_output",
        "label": "Preview Output",
        "category": "output",
        "description": "Preview result on map",
        "inputs": [{"handle": "input", "dataType": "any"}],
        "outputs": [],
    },
]

from .input_nodes import raster_input_node, vector_input_node
from .processing import (
    difference_node,
    ndvi_node,
    evi_node,
    savi_node,
    ndmi_node,
    ndwi_node,
    mndwi_node,
    nbr_node,
    bsi_node,
    ndsi_node,
    gndvi_node,
    rdvi_node,
    tvi_node,
    dvi_node,
    rvi_node,
    cigreen_node,
    cired_node,
    ndre_node,
    osavi_node,
    tsavi_node,
    vari_node,
    avi_node,
    arvi_node,
    ndti_node,
    wri_node,
    ui_node,
    nbr2_node,
    bai_node,
    csi_node,
    s3_node,
    hot_node,
    shadow_index_node,
    reclassify_node,
    clip_node,
    zonal_stats_node,
)
from .output_nodes import preview_output_node

NODE_REGISTRY = {
    "raster_input": raster_input_node,
    "vector_input": vector_input_node,
    "difference": difference_node,
    "ndvi": ndvi_node,
    "evi": evi_node,
    "savi": savi_node,
    "ndmi": ndmi_node,
    "ndwi": ndwi_node,
    "mndwi": mndwi_node,
    "nbr": nbr_node,
    "bsi": bsi_node,
    "ndsi": ndsi_node,
    "gndvi": gndvi_node,
    "rdvi": rdvi_node,
    "tvi": tvi_node,
    "dvi": dvi_node,
    "rvi": rvi_node,
    "cigreen": cigreen_node,
    "cired": cired_node,
    "ndre": ndre_node,
    "osavi": osavi_node,
    "tsavi": tsavi_node,
    "vari": vari_node,
    "avi": avi_node,
    "arvi": arvi_node,
    "ndti": ndti_node,
    "wri": wri_node,
    "ui": ui_node,
    "nbr2": nbr2_node,
    "bai": bai_node,
    "csi": csi_node,
    "s3": s3_node,
    "hot": hot_node,
    "shadow_index": shadow_index_node,
    "reclassify": reclassify_node,
    "clip": clip_node,
    "zonal_stats": zonal_stats_node,
    "preview_output": preview_output_node,
}
