_RASTER_IN = [{"handle": "raster_in", "dataType": "raster"}]
_RASTER_OUT = [{"handle": "raster_out", "dataType": "raster"}]
_RASTER_AB = [
    {"handle": "raster_a", "dataType": "raster", "label": "A"},
    {"handle": "raster_b", "dataType": "raster", "label": "B"},
]
_RASTER_UNARY = [{"handle": "raster", "dataType": "raster"}]

NODE_CATALOG = [
    # ── Inputs ────────────────────────────────────────────────────────────────
    {
        "type": "raster_input",
        "label": "Raster Input",
        "category": "input",
        "description": "Load a raster layer by slug",
        "inputs": [],
        "outputs": [{"handle": "raster_out", "dataType": "raster"}],
    },
    {
        "type": "vector_input",
        "label": "Vector Input",
        "category": "input",
        "description": "Load a vector layer by slug",
        "inputs": [],
        "outputs": [{"handle": "vector_out", "dataType": "vector"}],
    },
    # ── Arithmetic operators ──────────────────────────────────────────────────
    {
        "type": "add",
        "label": "Add",
        "category": "operators",
        "description": "Add two rasters (A + B)",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "subtract",
        "label": "Subtract",
        "category": "operators",
        "description": "Subtract raster B from A (A − B)",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "multiply",
        "label": "Multiply",
        "category": "operators",
        "description": "Multiply two rasters (A × B)",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "divide",
        "label": "Divide",
        "category": "operators",
        "description": "Divide raster A by B (A ÷ B)",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "power",
        "label": "Power",
        "category": "operators",
        "description": "Raise raster A to the power of B (A ^ B)",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "min",
        "label": "Min",
        "category": "operators",
        "description": "Per-pixel minimum of A and B",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "max",
        "label": "Max",
        "category": "operators",
        "description": "Per-pixel maximum of A and B",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    # ── Unary math ────────────────────────────────────────────────────────────
    {
        "type": "abs",
        "label": "Abs",
        "category": "operators",
        "description": "Absolute value of raster",
        "inputs": _RASTER_UNARY,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "sqrt",
        "label": "Square Root",
        "category": "operators",
        "description": "Square root of raster",
        "inputs": _RASTER_UNARY,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "log10",
        "label": "Log10",
        "category": "operators",
        "description": "Base-10 logarithm of raster",
        "inputs": _RASTER_UNARY,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "ln",
        "label": "Ln",
        "category": "operators",
        "description": "Natural logarithm of raster",
        "inputs": _RASTER_UNARY,
        "outputs": _RASTER_OUT,
    },
    # ── Trigonometric ─────────────────────────────────────────────────────────
    {
        "type": "sin",
        "label": "Sin",
        "category": "operators",
        "description": "Sine of raster values (radians)",
        "inputs": _RASTER_UNARY,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "cos",
        "label": "Cos",
        "category": "operators",
        "description": "Cosine of raster values (radians)",
        "inputs": _RASTER_UNARY,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "tan",
        "label": "Tan",
        "category": "operators",
        "description": "Tangent of raster values (radians)",
        "inputs": _RASTER_UNARY,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "asin",
        "label": "Asin",
        "category": "operators",
        "description": "Arcsine of raster values",
        "inputs": _RASTER_UNARY,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "acos",
        "label": "Acos",
        "category": "operators",
        "description": "Arccosine of raster values",
        "inputs": _RASTER_UNARY,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "atan",
        "label": "Atan",
        "category": "operators",
        "description": "Arctangent of raster values",
        "inputs": _RASTER_UNARY,
        "outputs": _RASTER_OUT,
    },
    # ── Logical / relational ──────────────────────────────────────────────────
    {
        "type": "lt",
        "label": "Less Than",
        "category": "operators",
        "description": "A < B (1 where true, 0 where false)",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "gt",
        "label": "Greater Than",
        "category": "operators",
        "description": "A > B (1 where true, 0 where false)",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "le",
        "label": "Less or Equal",
        "category": "operators",
        "description": "A <= B (1 where true, 0 where false)",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "ge",
        "label": "Greater or Equal",
        "category": "operators",
        "description": "A >= B (1 where true, 0 where false)",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "eq",
        "label": "Equal",
        "category": "operators",
        "description": "A == B (1 where true, 0 where false)",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "ne",
        "label": "Not Equal",
        "category": "operators",
        "description": "A != B (1 where true, 0 where false)",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "and",
        "label": "And",
        "category": "operators",
        "description": "Logical AND of A and B",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "or",
        "label": "Or",
        "category": "operators",
        "description": "Logical OR of A and B",
        "inputs": _RASTER_AB,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "if",
        "label": "If",
        "category": "operators",
        "description": "If condition > 0 use true raster, else false raster",
        "inputs": [
            {"handle": "condition", "dataType": "raster", "label": "Condition"},
            {"handle": "true", "dataType": "raster", "label": "True"},
            {"handle": "false", "dataType": "raster", "label": "False"},
        ],
        "outputs": _RASTER_OUT,
    },
    # ── AHP Weighted Overlay ──────────────────────────────────────────────────
    {
        "type": "ahp",
        "label": "AHP Weighted Overlay",
        "category": "operators",
        "description": "Pairwise comparison matrix → weights → normalised weighted sum (0-1)",
        "inputs": [
            {"handle": "A", "dataType": "raster", "label": "A"},
            {"handle": "B", "dataType": "raster", "label": "B"},
            {"handle": "C", "dataType": "raster", "label": "C"},
            {"handle": "D", "dataType": "raster", "label": "D"},
            {"handle": "E", "dataType": "raster", "label": "E"},
            {"handle": "F", "dataType": "raster", "label": "F"},
            {"handle": "G", "dataType": "raster", "label": "G"},
            {"handle": "H", "dataType": "raster", "label": "H"},
        ],
        "outputs": _RASTER_OUT,
    },
    # ── Raster Calculator ─────────────────────────────────────────────────────
    {
        "type": "raster_calculator",
        "label": "Raster Calculator",
        "category": "operators",
        "description": "Evaluate a band expression across one or more rasters (A_b1, A_b2, B_b1 …)",
        "inputs": [
            {"handle": "A", "dataType": "raster", "label": "A"},
            {"handle": "B", "dataType": "raster", "label": "B"},
            {"handle": "C", "dataType": "raster", "label": "C"},
        ],
        "outputs": _RASTER_OUT,
    },
    # ── Core processing ───────────────────────────────────────────────────────
    {
        "type": "difference",
        "label": "Difference",
        "category": "processing",
        "description": "Subtract raster B from raster A",
        "inputs": [
            {"handle": "raster_a", "dataType": "raster", "label": "A"},
            {"handle": "raster_b", "dataType": "raster", "label": "B"},
        ],
        "outputs": _RASTER_OUT,
    },
    # ── Vegetation indices ────────────────────────────────────────────────────
    {
        "type": "ndvi",
        "label": "NDVI",
        "category": "processing",
        "description": "Normalized Difference Vegetation Index (NIR−Red)/(NIR+Red)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "evi",
        "label": "EVI",
        "category": "processing",
        "description": "Enhanced Vegetation Index — reduces atmospheric distortion",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "savi",
        "label": "SAVI",
        "category": "processing",
        "description": "Soil-Adjusted Vegetation Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "gndvi",
        "label": "GNDVI",
        "category": "processing",
        "description": "Green NDVI — uses green band instead of red",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "rdvi",
        "label": "RDVI",
        "category": "processing",
        "description": "Renormalized Difference Vegetation Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "tvi",
        "label": "TVI",
        "category": "processing",
        "description": "Triangular Vegetation Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "dvi",
        "label": "DVI",
        "category": "processing",
        "description": "Difference Vegetation Index (NIR−Red)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "rvi",
        "label": "RVI",
        "category": "processing",
        "description": "Ratio Vegetation Index (NIR/Red)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "vari",
        "label": "VARI",
        "category": "processing",
        "description": "Visible Atmospherically Resistant Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "avi",
        "label": "AVI",
        "category": "processing",
        "description": "Advanced Vegetation Index — cube-root formulation",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "arvi",
        "label": "ARVI",
        "category": "processing",
        "description": "Atmospherically Resistant Vegetation Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Chlorophyll ────────────────────────────────────────────────────────────
    {
        "type": "cigreen",
        "label": "CI Green",
        "category": "processing",
        "description": "Chlorophyll Index Green (NIR/Green − 1)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "cired",
        "label": "CI Red",
        "category": "processing",
        "description": "Chlorophyll Index Red Edge (NIR/Red − 1)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "ndre",
        "label": "NDRE",
        "category": "processing",
        "description": "Normalized Difference Red Edge",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Soil-adjusted ─────────────────────────────────────────────────────────
    {
        "type": "osavi",
        "label": "OSAVI",
        "category": "processing",
        "description": "Optimized Soil-Adjusted Vegetation Index (L=0.16)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "tsavi",
        "label": "TSAVI",
        "category": "processing",
        "description": "Transformed Soil-Adjusted Vegetation Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Moisture ──────────────────────────────────────────────────────────────
    {
        "type": "ndmi",
        "label": "NDMI",
        "category": "processing",
        "description": "Normalized Difference Moisture Index (NIR−SWIR1)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Water ─────────────────────────────────────────────────────────────────
    {
        "type": "ndwi",
        "label": "NDWI",
        "category": "processing",
        "description": "Normalized Difference Water Index (Green−NIR)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "mndwi",
        "label": "MNDWI",
        "category": "processing",
        "description": "Modified NDWI (Green−SWIR)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "wri",
        "label": "WRI",
        "category": "processing",
        "description": "Water Ratio Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "s3",
        "label": "S3",
        "category": "processing",
        "description": "S3 water index using Green, NIR, SWIR",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Urban / Built-up ──────────────────────────────────────────────────────
    {
        "type": "ui",
        "label": "UI",
        "category": "processing",
        "description": "Urban Index (SWIR2−NIR)/(SWIR2+NIR)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Burn / Fire ───────────────────────────────────────────────────────────
    {
        "type": "nbr",
        "label": "NBR",
        "category": "processing",
        "description": "Normalized Burn Ratio (NIR−SWIR2)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "nbr2",
        "label": "NBR2",
        "category": "processing",
        "description": "Normalized Burn Ratio 2 (SWIR1−SWIR2)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "bai",
        "label": "BAI",
        "category": "processing",
        "description": "Burned Area Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "csi",
        "label": "CSI",
        "category": "processing",
        "description": "Char Soil Index (SWIR1/SWIR2)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Soil / Bare ───────────────────────────────────────────────────────────
    {
        "type": "bsi",
        "label": "BSI",
        "category": "processing",
        "description": "Bare Soil Index",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Snow ──────────────────────────────────────────────────────────────────
    {
        "type": "ndsi",
        "label": "NDSI",
        "category": "processing",
        "description": "Normalized Difference Snow Index (Green−SWIR)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Turbidity / Sediment ──────────────────────────────────────────────────
    {
        "type": "ndti",
        "label": "NDTI",
        "category": "processing",
        "description": "Normalized Difference Turbidity Index (Red−Green)",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Atmospheric ───────────────────────────────────────────────────────────
    {
        "type": "hot",
        "label": "HOT",
        "category": "processing",
        "description": "Haze Optimized Transformation",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "shadow_index",
        "label": "Shadow Index",
        "category": "processing",
        "description": "Shadow Index using visible bands",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    # ── Raster utilities ─────────────────────────────────────────────────────
    {
        "type": "reclassify",
        "label": "Reclassify",
        "category": "processing",
        "description": "Reclassify raster values by range rules",
        "inputs": _RASTER_IN,
        "outputs": _RASTER_OUT,
    },
    {
        "type": "clip",
        "label": "Clip",
        "category": "processing",
        "description": "Clip raster to vector mask",
        "inputs": [
            {"handle": "raster_in", "dataType": "raster"},
            {"handle": "vector_in", "dataType": "vector"},
        ],
        "outputs": _RASTER_OUT,
    },
    {
        "type": "zonal_stats",
        "label": "Zonal Stats",
        "category": "processing",
        "description": "Compute per-feature raster statistics",
        "inputs": [
            {"handle": "raster_in", "dataType": "raster"},
            {"handle": "vector_in", "dataType": "vector"},
        ],
        "outputs": [{"handle": "vector_out", "dataType": "vector"}],
    },
    # ── Output ────────────────────────────────────────────────────────────────
    {
        "type": "preview_output",
        "label": "Preview Output",
        "category": "output",
        "description": "Preview result on map",
        "inputs": [{"handle": "input", "dataType": "any"}],
        "outputs": [],
    },
]

from .input_nodes import raster_input_node, vector_input_node
from .processing import (
    # Arithmetic operators
    add_node, subtract_node, multiply_node, divide_node, power_node,
    min_node, max_node,
    # Unary math
    abs_node, sqrt_node, log10_node, ln_node,
    # Trig
    sin_node, cos_node, tan_node, asin_node, acos_node, atan_node,
    # Logical / relational
    lt_node, gt_node, le_node, ge_node, eq_node, ne_node,
    and_node, or_node, if_node,
    # AHP weighted overlay
    ahp_node,
    # Raster calculator
    raster_calculator_node,
    # Core processing
    difference_node,
    # Spectral indices
    ndvi_node, evi_node, savi_node, ndmi_node, ndwi_node, mndwi_node,
    nbr_node, bsi_node, ndsi_node,
    gndvi_node, rdvi_node, tvi_node, dvi_node, rvi_node,
    cigreen_node, cired_node, ndre_node,
    osavi_node, tsavi_node,
    vari_node, avi_node, arvi_node,
    ndti_node, wri_node, ui_node,
    nbr2_node, bai_node, csi_node, s3_node,
    hot_node, shadow_index_node,
    # Utilities
    reclassify_node, clip_node, zonal_stats_node,
)
from .output_nodes import preview_output_node

NODE_REGISTRY = {
    "raster_input": raster_input_node,
    "vector_input": vector_input_node,
    # Arithmetic operators
    "add": add_node,
    "subtract": subtract_node,
    "multiply": multiply_node,
    "divide": divide_node,
    "power": power_node,
    "min": min_node,
    "max": max_node,
    # Unary math
    "abs": abs_node,
    "sqrt": sqrt_node,
    "log10": log10_node,
    "ln": ln_node,
    # Trig
    "sin": sin_node,
    "cos": cos_node,
    "tan": tan_node,
    "asin": asin_node,
    "acos": acos_node,
    "atan": atan_node,
    # Logical / relational
    "lt": lt_node,
    "gt": gt_node,
    "le": le_node,
    "ge": ge_node,
    "eq": eq_node,
    "ne": ne_node,
    "and": and_node,
    "or": or_node,
    "if": if_node,
    # AHP weighted overlay
    "ahp": ahp_node,
    # Raster calculator
    "raster_calculator": raster_calculator_node,
    # Core processing
    "difference": difference_node,
    # Spectral indices
    "ndvi": ndvi_node,
    "evi": evi_node,
    "savi": savi_node,
    "ndmi": ndmi_node,
    "ndwi": ndwi_node,
    "mndwi": mndwi_node,
    "nbr": nbr_node,
    "bsi": bsi_node,
    "ndsi": ndsi_node,
    "gndvi": gndvi_node,
    "rdvi": rdvi_node,
    "tvi": tvi_node,
    "dvi": dvi_node,
    "rvi": rvi_node,
    "cigreen": cigreen_node,
    "cired": cired_node,
    "ndre": ndre_node,
    "osavi": osavi_node,
    "tsavi": tsavi_node,
    "vari": vari_node,
    "avi": avi_node,
    "arvi": arvi_node,
    "ndti": ndti_node,
    "wri": wri_node,
    "ui": ui_node,
    "nbr2": nbr2_node,
    "bai": bai_node,
    "csi": csi_node,
    "s3": s3_node,
    "hot": hot_node,
    "shadow_index": shadow_index_node,
    "reclassify": reclassify_node,
    "clip": clip_node,
    "zonal_stats": zonal_stats_node,
    "preview_output": preview_output_node,
}
